apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitwarden-vol
spec:
  capacity:
    storage: 9Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs 
  nfs:
    server: 192.168.50.3
    path: "/mnt/tank/nfs/kuberneties/bitwarden"
